name: "update status"
on:
   workflow_dispatch:
jobs:
 inits:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
#      - name: cache_imagemagick
#        uses: actions/cache@v4
#        with:
#          path: /usr/local/bin
#          key: ${{ runner.os }}-imagemagick-
#          restore-keys: |
#            ${{ runner.os }}-imagemagick-

      - name: execute
        run: |
         sudo apt update && sudo apt upgrade
         command -v convert &>/dev/null || sudo apt install imagemagick -y
         bash main.sh
         bash main_stats.sh
        
      - name: update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "updated"
          repository: .
          file_pattern: ./*.jpg ./*.png ./*.gif README.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
